### ISSUE TITLE
MQTT issue 

### ISSUE THREAD

**Issue by coltonhugg** [m5stack/uiflow-micropython#22]
Unlike version 1.0 when the device "applies for messaging" for MQTT no other action can be performed aka a button press this severely limits the use of MQTT with m5stack

**Comment by lbuque** [comment]
@coltonhugg This issue will be fixed in the next version.

**Comment by felmue** [comment]
Hello @coltonhugg 

in the meantime maybe have a look at this Project Zone example: _M5Dial_WiFi_MQTT_UIFlow2.0.1_

The 'trick' is to use `mqtt_client.check_msg()` instead of `mqtt_client.wait_msg()`.

Thanks
Felix

**Comment by lbuque** [comment]
@coltonhugg @felmue This issue was resolved in 2.0.9.
