### ISSUE TITLE
I2C refactoring breaks ENV IV unit

### ISSUE THREAD

**Issue by felmue** [m5stack/uiflow-micropython#23]
Hello M5Stack engineers

the recent I2C refactoring (`machine_i2c.c`) in UIFlow v2.0.8 seems to break the ENV IV unit.

Please see this [post](https://community.m5stack.com/topic/6580/env-iv-unit-not-working-with-firmware-v2-0-8).

BTW: Compiling my own UIFlow v2.0.8 firmware for M5Dial, but replacing `machine_i2c.c` with the previous version from [here](https://github.com/m5stack/uiflow-micropython/blob/4245afd966dd219b36e4c518409d19a4f354cd91/m5stack/machine_i2c.c) makes the ENV IV unit work again.

Thanks
Felix

**Comment by lbuque** [comment]
@felmue Processing.

**Comment by lbuque** [comment]
@felmue This issue was resolved in 2.0.9.

**Comment by felmue** [comment]
Hello @lbuque 

thank you for fixing the issue. I just ran a test with M5Dial and ENV IV and I can confirm v2.0.9 fixes the issue.

Thanks
Felix

**Comment by BitcoinRaven** [comment]
Im facing same issue with CoreS3 and ENV IV with v2.0.9.

**Comment by felmue** [comment]
Hello @BitcoinRaven 

I cannot recreate the issue you are seeing. I tested with M5CoreS3 (UIFlow firmware v2.0.9) and ENV IV and it works for me.

- Are you sure you burned v2.0.9 onto your M5CoreS3?
- What is the error you are getting?

Thanks
Felix
