### ISSUE TITLE
Missing M5Things?

### ISSUE THREAD

**Issue by rodrigob** [m5stack/uiflow-micropython#27]
I am exploring the codebase of https://github.com/m5stack/uiflow-micropython (UiFlow2), 
and I see multiple mentions of M5Things however I could not find its code.

https://github.com/search?q=org%3Am5stack%20M5Things&type=code
does not return any results (only mentions/usage, not definition)

Could someone point me to it?

(see also https://community.m5stack.com/topic/6733/m5things )

**Comment by lbuque** [comment]
M5Things is private.

**Comment by rodrigob** [comment]
Would be nice to have this added in the documentation. Ideally having the API documented (even if implementation is closed source) would be nice too.
