### ISSUE TITLE
Installing third-party libraries with UIFlow IDE 

### ISSUE THREAD

**Issue by MaxRondelli** [m5stack/uiflow-micropython#29]
Hi there, 

I am using a M5Stack Gray with ESP32 core on flow web IDE. The connection and firmware installation were successful.

Due to the aim of my project, I need some third-party libraries, such as Numpy (which can be ulab for micropython) and TensorFlowLite, to import and interpreter my ML model. 

Is there a way of doing that?  Is there a way to import the modules necessary? 

Thank you for your time.

**Comment by lbuque** [comment]
@MaxRondelli Dynamic loading of C modules is not supported.
All the third-party libraries you mentioned need to compile their C source code into the firmware.
